# Generated by Django 4.1.7 on 2023-03-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
